### ISSUE TITLE
Frost protection icon 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#242] opened 2020-05-23 16:57 UTC
today one of my wireless sensors was out of battery power and that zone went into frost protection but no icon was showing on gui only boiler icon was red and upon physical inspection of manifold i realized my ground floor heating was on and sensors hadn't reported as it was out of power. i think this is bug, also i think if i frost protection temperature is set to 0 then it will be disabled. may be changing info text for this as well. 
`$lang['frost_protection_text'] = "System will protect itself against frost. To Disable projection you can set the temperature to 0";`

**Comment by pihome-shc** [comment] 2020-05-27 21:12
@dvdcut i will do some testing later and suggest the update.

**Comment by pihome-shc** [comment] 2020-05-27 23:11
@dvdcut, 
if zone temperature sensors do not send reading for while and db_cleanup.php remove 3 days old value from the point db_cleanup.php run.  
```
$query = "DELETE FROM messages_in WHERE datetime < DATE_SUB(curdate(), INTERVAL 3 DAY);";
```
i this issue is caused by interval between db_cleanup.php and value being 24h older. hence still shows in zone but boiler.php kick start zone as frost protection. 

as far as frost protection disable goes that should do as well. if value is set to 0 then frost protection is disable. 
can you do pull request for change in language please. 



![image](https://user-images.githubusercontent.com/33334232/83078976-ba44ac00-a072-11ea-8c0b-f31e0f290a90.png)

**Comment by pihome-shc** [comment] 2020-05-27 23:29
another option would be to change db_cleanup.php crontab to 10 0 * * * from 0 2 * * * or even run job once every 1 hour.

**Comment by dvdcut** [comment] 2020-05-29 13:46
if that is the case then fix is easy, why not remove old values more frequently ?

**Comment by pihome-shc** [comment] 2020-05-29 18:45
@dvdcut yes it would best to run cleanup cronjob more frequently, may be run it once every hour. i m going to change this in PiHome image as well.

**Comment by pihome-shc** [comment] 2020-06-03 00:02
closing this issue now, text is already added in frost protection model and clean-up job will be added once every hour in next img file for raspberry pi.

**Closed by pihome-shc** 2020-06-03 00:02 UTC
Labels: bug
