### ISSUE TITLE
Icon for deadband 

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#49] opened 2019-08-23 01:17 UTC
This one is small GUI bug. When zone heating isn't starting due to dead-band or weather temperature compensation than on GUI its very misleading and it shows schedule icon as but boiler icon stay blue, I think it would be nice to display why heating/boiler isn’t starting i.e icon for dead-band and weather temperature compensation. 
@aszumski

**Comment by pihome-shc** [comment] 2019-08-27 20:19
@dvdcut  i think green leaf would be best option when zone is in deadband or in weather factor, i know 
@aszumski worked on deadband but homelist.php does not have any reference to deadband this need some modifications to homelist and add following icon. 
<i class="glyphicon glyphicon-leaf green"></i>

**Comment by aszumski** [comment] 2019-08-28 07:22
I think homelist needs little bit of rework all together.
It's out of sync with boiler.php
It doesn't take account of deadband, temperature correction, schedule night rollover bug that was fixed in boiler php etc.
Except that it's not even easy to copy code from boiler into homelist cause boiler uses views and homelist tables directly.

**Comment by aszumski** [comment] 2019-08-28 11:08
@dvdcut had a same idea in my head. That way code is not replicated and doesn't get out of sync when you update some functionality in boiler PHP.

Also taught about using SQL memory tables for it and maybe some other tables that are only used to exchange information between pieces of code and not to store configuration/history information.
It would save writes to the SD card,and maybe some reads (I expect there is some caching built in to database anyway). But not sure if it's worth the haste, you need to initialize those tables  etc.

**Comment by pihome-shc** [comment] 2019-08-28 17:32
@dvdcut, @aszumski 
i know where you both are coming from, if we have table for zone status and then its only one query and loading/refreshing of homelist.php would be lot faster. This improvement requires some thinking.
 
@aszumski i never used sql memory tables and dont know what it takes to configure/use them. i agree homelist.php and boiler.php isnt in sync 100% and one is using table view and another is using direct tables, can not recall why it was this way but so far havent seen any bug or issue but willing to work with you on improving this.

**Comment by pihome-shc** [comment] 2020-03-01 14:35
i was looking into this later last night, i think this might work, haven't tested it intensively but this part needs to go just before other schedule condition. 

```
              else if (($sch_status == 1) && ($room_c < ($schedule_c - $weather_fact)) OR ($fired_status == 0)) {
                  //We are scheduled and heating
                  $status='orange';
                  $shactive='fa-leaf green';
                  $shcolor='';
                  $target=number_format(DispTemp($conn,$schedule_c),0) . '&deg;';
              }
```

**Comment by pihome-shc** [comment] 2020-06-06 14:27
@dvdcut  / @aszumski any thoughts on this?

**Comment by aszumski** [comment] 2020-06-09 10:18
@pihome-shc I will have look at improving this.
Just resynced my pihome  code with the master.
I don't have dev system, and was not allowed to go near the system during heating season :)

**Comment by pihome-shc** [comment] 2020-06-09 18:05
@aszumski thank you, i tried making changes but failed to cover all aspect.

**Comment by aszumski** [comment] 2020-06-11 13:50
@pihome-shc 
I've made changes and it seems to work OK but I would like someone else to run some tests because there is lots of changes specially in homelist.
Everyone is welcome to test it and come back with issues.
I've created zone_mode variable that is passed to memory SQL table along with zone alarm flags etc. so zone displayed status always matches actual.
Currently there are only 2 SQL queries to get zone data in zonelist.php
To test it create table:
```
CREATE TABLE `zone_current_state` (
 `id` int(11) NOT NULL,
 `mode` int(11) DEFAULT NULL,
 `status` tinyint(1) DEFAULT NULL,
 `temp_reading` decimal(4,1) DEFAULT NULL,
 `temp_target` decimal(4,1) DEFAULT NULL,
 `temp_cut_in` decimal(4,1) DEFAULT NULL,
 `temp_cut_out` decimal(4,1) DEFAULT NULL,
 `controler_fault` int(1) DEFAULT NULL,
 `controler_seen_time` timestamp NULL DEFAULT NULL,
 `sensor_fault` int(1) DEFAULT NULL,
 `sensor_seen_time` timestamp NULL DEFAULT NULL,
 `sensor_reading_time` timestamp NULL DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8
```
And replace boiler.php and zonelist.php with attached below:
[For review.zip](https://github.com/pihome-shc/pihome/files/4765005/For.review.zip)

Note that status of zones is updated by boiler.php so zone status on homescreen refreshes only when boiler.php runs (every minute).

zone_current_state records are created in boiler.php if they don't exist.
There is no code to remove records, as not needed, if zone is deleted record will remain there (not used) until next reboot (memory tables contents are dumped or rebooted).

I've also added small info about cut in/cut out temperatures on the zone screen (the one that you get when you click on the zone on the home screen) and additional text when there is coop start schedule active, zone is below cut in temperature and waiting for boiler start by other zone.

Please get back to me if you find any issues.

**Comment by dvdcut** [comment] 2020-06-11 14:18
@aszumski i did test on my system after creating table i can see it is gettin populated but homelist.php have no changes, may be you attached the old one.

**Comment by aszumski** [comment] 2020-06-11 16:12
@dvdcut 
Attached wrong one, updated file below:

[For review.zip](https://github.com/pihome-shc/pihome/files/4765964/For.review.zip)


Found small issue already. if zone is not enabled it will not update temperature reading as boiler.php only processes enabled zones. Fixed in the attached file (added back query for getting temperature reading in homelist).

**Comment by dvdcut** [comment] 2020-06-11 17:34
Zone Main Mode
0 - idle
10 - fault
20 - frost
30 - over temperature
40 - holiday
50 - night-climate
60 - boost
70 - override
80 - scheduled
90 - away
100 - hysteresis

Code 100 works as expected, 
schedule: set zone temperature 20, current zone temperature 19.5
when schedule is enabled for one zone and not for other zones it set the code to 40 for all zone where schedule is disabled. whereas it should have been 0. 

schedule: set zone temperature 50, current zone temperature 50.0
mode is 0 but with blue dot, when i look into zone_current_state table i can see tem_reading 48.9, temp_target 50.0, temp_cut_in 48.9, temp_cut_out 49.4

**Comment by aszumski** [comment] 2020-06-11 23:16
@dvdcut 
You are too fast :)
You need to give time for boiler.php to execute, 
First case tested and it had different bug, status of  zones that are disabled within schedule actually changed to holidays because of existing bug in boiler code:
```
if (isset($schedule['holidays_id'])) {
    $sch_holidays = '1';
}
```
replaced with
```
if ($schedule['holidays_id']>0) {
				$sch_holidays = '1';
			}else{
				$sch_holidays = '0';
			}
```
isset() gives 0 if value is null, and holidays_id is 0 for non holidays schedules so check returned always true.

For second case looks like boiler script didn't execute yet cause you have temperature reading 48.9 (you got 50 on home screen but boiler script didn't execute yet) temp_cut_in 48.9, temp_cut_out 49.4 in current state table, mode should be 41 or 42 in that case (schedule with temperature within deadband with zone running or not) because you got blue indicator it means zone was not running, if you would execute script with reading 48.8 or below it would run zone untill you execute sctipt with value 49.4 or above.
Currently i have indicator colours:
running- red
stopped within deadband or coop start below cut in - dark blue (coop start waiting for boiler will show green leaf icon instead schedule icon)
 stopped holiday or away - blue
stopped idle of fault - black
stopped other cases (temperature reached, overtemperature etc) - orange

Colours ar the same as before changes, was not sure what colours we want to use for stopped within deadband and coop start waiting for boiler.

Did some more testing.
One question is it intended that if night climate is enabled zones that are not enabled in night climate use standard schedule (that's how it works now), or maybe they should be idle.
Never used that function and not sure what it suppose to do, I'm using normal schedules for the night because of coop start functionality.

Later we might look at speeding up cron job for he boiler script,
but we would have to change message_out table to memory table, and maybe don't trigger sending commands through the gateway every script execution, but at set time intervals (if the command doesn't change) and if the command changes, this way we would not hammer SD card/gateway that much.

**Comment by pihome-shc** [comment] 2020-06-12 11:49
@aszumski so far very good, i can see blue dot but no green leaf 

![image](https://user-images.githubusercontent.com/33334232/84499587-d10e1400-acaa-11ea-81cc-74b3b18bc8f8.png)

Here is mysql table. 
![image](https://user-images.githubusercontent.com/33334232/84499744-10d4fb80-acab-11ea-8b3e-148bca063ba1.png)

**Comment by aszumski** [comment] 2020-06-12 13:47
@pihome-shc to get green leaf you need to be below cut in temperature -coop start waiting for boiler start, when between cut in and cut out it shows standard schedule icon (and indicator is red or blueinfo dependent on zone active or not), but it's up for discussion what icons/colours we want to use

**Comment by aszumski** [comment] 2020-06-12 13:57
I did it with indicator colour rather then icon cause you can be within deadband in schedule, night climate, boost, override and frost protection. You still want to see what mode is running when you are within deadband (between cut in and cut out).

**Comment by pihome-shc** [comment] 2020-06-13 10:34
@aszumski got your point and understood, good thinking on leaving icon (schedule, night climate, boost, override and frost protection), but i think change the colour from blue to green would be good option, as red is only when zone is calling for heat.

**Comment by pihome-shc** [comment] 2020-06-13 10:35
@aszumski can you do pull request so it get included and i can do testing on one customer system he got 12 zones and would be good test.

**Comment by pihome-shc** [comment] 2020-06-16 20:42
something is wrong with mysql table creation code. here is the output from update_db.php 
```
2020-06-16 21:29:23 - CREATE TABLE IF NOT EXISTS `zone_current_state` (
  `id` int(11) NOT NULL,
  `mode` int(11) ,
  `status` tinyint(1) ,
  `temp_reading` decimal(4,1) ,
  `temp_target` decimal(4,1) ,
  `temp_cut_in` decimal(4,1) ,
  `temp_cut_out` decimal(4,1) ,
  `controler_fault` int(1) ,
  `controler_seen_time` timestamp NULL ,
  `sensor_fault` int(1) ,
  `sensor_seen_time` timestamp NULL ,
  `sensor_reading_time` timestamp NULL ,
  PRIMARY KEY (`id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;
2020-06-16 21:29:23 - ALTER TABLE `zone_logs` MODIFY `boiler_log_id` int(11);
2020-06-16 21:29:23 - ALTER TABLE `zone_logs` MODIFY `status` int(11);
2020-06-16 21:29:23 - ALTER TABLE `zone_logs` MODIFY `zone_id` int(11);
2020-06-16 21:29:23 - ALTER TABLE `zone_type` MODIFY `category` int(11);
2020-06-16 21:29:23 - ALTER TABLE `zone_type` MODIFY `type` char(50) COLLATE utf8_bin;
2020-06-16 21:29:23
Existing Database Table Structures will be amended.
Are you sure you want to do this?  Type 'yes' to continue?
---------------------------------------------------------------
yes
2020-06-16 21:29:27 - Creating Dump File for Exiting Database.
2020-06-16 21:29:29 - Compressing Database Dump File pihome_2020-06-16_21-29-27.sql
2020-06-16 21:29:36 - Compressed Database Dump File pihome_2020-06-16_21-29-29.zip
2020-06-16 21:29:36 - Applying Updates to Database.
MySQL Database Error with Query ALTER TABLE `piconnect_logs` MODIFY PRIMARY KEY (`id`);
:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PRIMARY KEY (`id`)' at line 1
MySQL Database Error with Query ALTER TABLE `zone` DROP `boiler_id`;
:Cannot drop index 'FK_zone_boiler': needed in a foreign key constraint
MySQL Database Error with Query ALTER TABLE `zone` MODIFY `sp_deadband` float NOT NULL;
:Data truncated for column 'sp_deadband' at row 5
MySQL Database Error with Query CREATE TABLE IF NOT EXISTS `zone_current_state` (
  `id` int(11) NOT NULL,
  `mode` int(11) ,
  `status` tinyint(1) ,
  `temp_reading` decimal(4,1) ,
  `temp_target` decimal(4,1) ,
  `temp_cut_in` decimal(4,1) ,
  `temp_cut_out` decimal(4,1) ,
  `controler_fault` int(1) ,
  `controler_seen_time` timestamp NULL ,
  `sensor_fault` int(1) ,
  `sensor_seen_time` timestamp NULL ,
  `sensor_reading_time` timestamp NULL ,
  PRIMARY KEY (`id`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8;
:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`id` int(11) NOT NULL,
  `mode` int(11) ,
  `status` tinyint(1) ,
  `temp_rea' at line 2
2020-06-16 21:29:37 - Database Updates Applied
2020-06-16 21:29:37 - Importing SQL Table View File to Database, This could take few minuts.
2020-06-16 21:29:37 - DataBase File /var/www/MySQL_Database/MySQL_View.sql Imported Successfully
2020-06-16 21:29:37 - Update Version: 1.75
2020-06-16 21:29:37 - Update Build: 040620
2020-06-16 21:29:37 - MySQL Update DataBase Script Ended
****************************************************************************************
root@pihome:/var/www/MySQL_Database#
```

**Comment by aszumski** [comment] 2020-06-16 23:48
Created new pull request with the fix, not sure what was the cause,
@pihome-shc  is there a reason why we pull sql config file from github instead of using local one when we run update script?
Script has to be modified to test the changes locally.

**Comment by pihome-shc** [comment] 2020-06-16 23:49
@aszumski thank you for fixing this. i will do some testing now and let you know if any further issues.

**Comment by pihome-shc** [comment] 2020-06-16 23:57
re: update script, @aszumski that is valid point, i don't remember why GitHub was selected as source for comparison, may be @twa127 can shed some light on this. if someone didnt update (git pull origin) from github source then updating database from GitHub may break their system.

**Comment by twa127** [comment] 2020-06-17 06:25
As I remember :-) the idea was that the update script could be run to ensure that the database format is updated without corrupting the existing system data where the github version is the current image

**Comment by pihome-shc** [comment] 2020-06-17 19:29
i think updating software part is still pretty much manual process ie. cd /var/www/ and then git pull origin and so far it this process is working fine.

**Closed** 2020-07-02 19:02 UTC
Labels: enhancement
