### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by dvdcut** [pihome-shc/pihome#291] opened 2020-06-23 14:20 UTC
i thought its best to open issue for charts only related work. charts need cleanup, here are the files involved in all charts and their functions: 

chart.php - mail file to load graphs
chartlist.php - daily temperature chart
boilerlist.php - porcess and display usage table list
monthusage.php - Boiler Usage graph 
battery_usage.php - display battery usage graph
chartfooter.php -  processing the data and making charts array etc. 
chartload.php - Not used 

i think reduce the number of files, if we can, if not then rename them to start with chart_<function>.php so all the charts related files are visually same. 

@twa127 did pull request: Initial tidy up of charting #290

**Comment by twa127** [comment] 2020-06-23 14:44
after initial tidy we have:

chart.php - main file
chartload.php - processing the data and making charts array etc.
boilerlist.php - process and display usage table list
daily_usage.php - display the main logs page on entry
monthusage.php - Boiler Usage graph
battery_usage.php - display battery usage graph

**Comment by twa127** [comment] 2020-06-23 14:48
Also need a better way to load, so that we can display a loading message as dataset creation can take a long time

**Comment by dvdcut** [comment] 2020-06-23 15:04
GitHub eat my file name, i was referring to file name as: 

- chart.php
- chart_load.php
- chart_boilerlist.php
- chart_dailyusage.php
- chart_monthusage.php
- chart_batteryusage.php

this way we have all the files in same location when you see them, looks tidy

**Comment by twa127** [comment] 2020-06-23 15:05
looks good to me

**Comment by dvdcut** [comment] 2020-06-23 15:13
@twa127 agree, loading needs to be displayed for better user experience,

**Comment by twa127** [comment] 2020-06-23 15:27
changed commit to reflect the names above

**Comment by dvdcut** [comment] 2020-06-23 15:47
right now when i click charts it loads all the data (all 4 types of data even i m only need one type i.e daily temperature graph). can it be modified some way so it only loads the part we want to look i.e if i click chart it loads temperature chars but as soon as i click on battery usage it loads that part from db, if we can implement this it would be lot faster and lighter.

**Comment by twa127** [comment] 2020-06-23 16:31
I think the only thing you could loose would be the battery voltage dataset, boilerlist and monthlyusage get the data on entry

**Comment by twa127** [comment] 2020-06-23 17:05
on my live system opening the chart now takes approx 40 seconds to open, but if I drop the battery voltage dataset creation from chart_load.php it drops to only 5 seconds,

**Comment by pihome-shc** [comment] 2020-06-23 17:38
some people are complaining about this slow loading of graphs i think we have to drop battery part untill we can make that on demand.

**Comment by pihome-shc** [comment] 2020-06-23 20:38
is it only me or you also can not see charts? when i click on chart icon no temperature charts and when i click on second icon it loads boost list and not graph for boiler usage either.

**Comment by twa127** [comment] 2020-06-23 21:13
Sorry forgot to update to update the filename in footer.php

**Comment by pihome-shc** [comment] 2020-06-23 21:21
@twa127 still the same, even after last update.

**Comment by twa127** [comment] 2020-06-23 21:39
committed another fix

**Comment by pihome-shc** [comment] 2020-06-23 21:49
Something not right, see attached images

**Comment by twa127** [comment] 2020-06-23 21:55
no image

**Comment by pihome-shc** [comment] 2020-06-23 22:02
dont know why email images was removed by github. 

![image](https://user-images.githubusercontent.com/33334232/85469320-6c559200-b5a5-11ea-9c5d-96af1b339d2a.png)

![image](https://user-images.githubusercontent.com/33334232/85469357-79728100-b5a5-11ea-966e-10c363e1e3b1.png)

![image](https://user-images.githubusercontent.com/33334232/85469410-868f7000-b5a5-11ea-9e20-e4be48af7533.png)

**Comment by twa127** [comment] 2020-06-23 22:04
I'll copy code to my Pi setup and get back to you

**Comment by twa127** [comment] 2020-06-23 22:11
quick test and it worked okay on my Pi, I'll download files from github

**Comment by pihome-shc** [comment] 2020-06-23 22:18
this is very odd, i just did sudo git clone https://github.com/pihome-shc/pihome "/var/www" on new folder and load pihome and still the same result

**Comment by twa127** [comment] 2020-06-23 22:24
Can you try using the attached for chart_boilerlist.php
[chart_boilerlist.zip](https://github.com/pihome-shc/pihome/files/4822268/chart_boilerlist.zip)

**Comment by twa127** [comment] 2020-06-23 22:24
off to bed catch you in the morning

**Comment by pihome-shc** [comment] 2020-06-23 22:30
@twa127 attached chart_boilerlist.zip is working but its not the same as you github.

**Comment by twa127** [comment] 2020-06-24 06:13
Sorry copied the wrong file when I changed the file names, committed a correction

**Comment by twa127** [comment] 2020-06-25 13:35
To reduce loading time can I suggest that we only display 1 graph for battery, currently both graphs display exactly the same info but with different scaling of the y axis

**Comment by pihome-shc** [comment] 2020-06-25 16:53
Agree, I think we cal leave Battery % graph in and drop voltage graph.

Kind Regards
PiHome Smart Heating

**Comment by twa127** [comment] 2020-06-26 06:41
Hi,

Do we want to re-introduce battery level graph after update by @dvdcut ?

**Comment by pihome-shc** [comment] 2020-06-26 20:26
@twa127 
#298 right now there is no record for min_voltage for sensors. it is left null we can change temperature sketch to send this value on startup and capture this and record it. 

another suggestion: for time being we can drop battery graph altogether,

**Comment by twa127** [comment] 2020-06-26 20:53
Hi,

I think that min_voltage should be set in node alerts gui, perhaps changed to min_level to match the graph and also used in email notifications. I use a mix of battery and mains powered sensors hence the check if NULL or perhaps 0

**Comment by pihome-shc** [comment] 2020-06-26 21:14
Good thinking, one question how to add minimum value there? If we modify gateway.py then it cannot distinguishes between mains powered vs battery powered.  Are thinking to add option for battery level graph same as zone graph?

**Comment by twa127** [comment] 2020-06-26 21:23
Don't need to do anything in gateway just use same process as Notice Interval and set in Edit Node Alert Settings

**Comment by dvdcut** [comment] 2020-06-27 11:58
i dont mind if you want to drop battery charts. 
@twa127 setting alert for battery level still wouldn't make difference, i mean that would create alert but how to enable/disable battery graph? 
i suggest adding bat_graph_it column in nodes table and under settings->sensors add checkbox for battery level graph

**Comment by twa127** [comment] 2020-06-27 14:39
The battery charts kind of have a one time use for working out how fast the fall off is and for determining a threshold point for sending alerts.

What I think is the issue is that all the data gets loaded by chart_load.php, it would be good if chart_batteryusage.php loaded its own data, but I'm struggling to make this work.

I would like to change the min_voltage column in the nodes table to min_value as an INTEGER type if you agree and make this editable in the Node Alert setting

![node_alert](https://user-images.githubusercontent.com/46624596/85924769-30177f80-b88c-11ea-85da-289230f71c09.JPG)

**Comment by pihome-shc** [comment] 2020-06-27 15:08
@twa127 yes that shouldn't have any issues as that value isnt used anywhere. @dvdcut have not issues removing battery chart and we can workout to make it faster, as you said battery usage is not something you want to see everyday. important bit is how to alert user of battery level rather show how it is used over time.

**Comment by twa127** [comment] 2020-06-27 15:25
okay I'll go ahead and code the alert stuff

**Comment by leeoniya** [comment] 2020-06-27 15:30
as someone who's interested in both home automation and charting, thought i'd shamelessly plug https://github.com/leeoniya/uPlot in case this project was open to evaluating alternatives to Flot/Morris. cheers! `</hijack>`

**Comment by twa127** [comment] 2020-06-27 16:53
ah something else to keep me occupied during lockdown :-)

**Comment by pihome-shc** [comment] 2020-06-28 22:43
@twa127, 
after your changes here is my node table before and after changes, it set to repeater column to null, sketch version to 0 and ms version swapped with sketch version. i think its shifted one column to left. 

![image](https://user-images.githubusercontent.com/33334232/85960051-5cb8bd80-b998-11ea-84f8-2874141b5931.png)

after apply changes, 
![image](https://user-images.githubusercontent.com/33334232/85960061-76f29b80-b998-11ea-9515-bfd8a6c389ec.png)

**Comment by twa127** [comment] 2020-06-29 07:59
hi,

Looks like you have not updated the nodes table definition to change the min_voltage decimal field to min_value INT(11)

**Comment by dvdcut** [comment] 2020-06-29 12:08
@pihome-shc i have done the update and it is working as expected. two things, first it did set repeater value to null and second. min_value is set to null, may be db_update.php script need some work to check these values 

![image](https://user-images.githubusercontent.com/53821067/86003195-5dd60300-ba09-11ea-8b0c-a2adce509ad8.png)

**Comment by twa127** [comment] 2020-06-29 14:18
Hi,

min_value will be set by the gateway script but only for the latest version of the temperature sensor sketch, not sure why repeater is set to nulll

**Comment by dvdcut** [comment] 2020-06-29 14:53
i think to update sketch in all nodes i need usb to ttl device :sweat: . i dont think over the air type of update implemented in any wireless nodes.

**Comment by twa127** [comment] 2020-06-29 15:02
I guess not too much of an issue short term as you can set min_value manually, the gateway script just sets an initial value when the node comes on-line

**Comment by twa127** [comment] 2020-07-01 19:04
Hi

attached a bit of php to load the zone_graphs table with the last 24 hours of temps, you need to pause the gateway script while it runs

[pop_zone_graphs.zip](https://github.com/pihome-shc/pihome/files/4859932/pop_zone_graphs.zip)

**Comment by pihome-shc** [comment] 2020-07-02 00:19
@twa127 your indentation is wrong, also you have some other errors on line 275, and 276. 


```
root@pihome:/var/www/MySQL_Database# python /var/www/cron/gateway.py
  File "/var/www/cron/gateway.py", line 265
    cur.execute('SELECT * FROM `zone_view` where sensors_id = (%s) AND sensor_child_id = (%s) LIMIT 1;', (node_id, child_sensor_id))
                                                                                                                                   ^
TabError: inconsistent use of tabs and spaces in indentation

```
i think correct lines are 

```
									print("5a: Adding Temperature Reading to Graph Table From Node ID:", node_id, " Child Sensor ID:", child_sensor_id)
									cur.execute('INSERT INTO zone_graphs(`sync`, `purge`, `zone_id`, `name`, `type`, `category`, `node_id`,`child_id`, `sub_type`, `payload`)')
									con.commit()
```

**Comment by pihome-shc** [comment] 2020-07-02 00:24
adding records to zone_graphs gives following error and gateway.py gets terminated. 

```
Size of the String Received:  41
Date & Time:                  Thu Jul  2 01:20:13 2020
Full String Received:         30;0;1;0;0;34.0
Full Statement Received:      ['30', '0', '1', '0', '0', '34.0\n']
Node ID:                      30
Child Sensor ID:              0
Message Type:                 1
Acknowledge:                  0
Sub Type:                     0
Pay Load:                     34.0
5: Adding Temperature Reading From Node ID: 30  Child Sensor ID: 0  PayLoad: 34.0
5a: Adding Temperature Reading to Graph Table From Node ID: 30  Child Sensor ID: 0
DB Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
More info in log file: /var/www/logs/main.log
Traceback (most recent call last):
  File "/var/www/cron/gateway.py", line 376, in <module>
    logging.exception(e)
NameError: name 'e' is not defined

```

**Comment by pihome-shc** [comment] 2020-07-02 01:52
@twa127 pop_zone_graphs.zip is alternate to update zone_graphs table?

**Comment by twa127** [comment] 2020-07-02 07:05
committed a fix for the gateway.py errors

pop_zone_graphs.php is just a script to copy the existing zone temperature readings from messages_in table to the new zone_graphs table for the last 24hours and where graph_it = 1, this is so that you don't start with an empty zone_graphs table and have to wait for it to re-fill over the next 24 hours.

I'd be interested to know if you see any improvement in the time taken to load the graphs, mine went from 10 seconds to about 5 seconds (slower if the boiler script was in the middle of executing)

**Comment by twa127** [comment] 2020-07-02 07:32
I've moved the removal of records after 24 hour from db_cleanup.php to gateway.py otherwise the we have to wait until 2AM when db_cleanup runs

**Comment by dvdcut** [comment] 2020-07-02 12:05
@twa127 are trying to reduce the size of query that is executed on chart load by copying temperature readings into zone_graphs table and using it for graph purpose?

**Comment by twa127** [comment] 2020-07-02 12:24
Hi

Yes that's the idea, the new table contains only zone records for the last 24 hours where graph_it = 1, so the query runs much faster. Also now only run 1 query to get the data for both heating and water, so a bit more performance gain. On my live system it is at least twice as fast to load the graphs page.

**Comment by twa127** [comment] 2020-07-02 13:21
Bye the way table zone-graphs is populated by the gateway script at the same time as messages_in, so this is back-end activity

**Comment by dvdcut** [comment] 2020-07-07 22:07
this issue can be closed if @twa127 is happy

**Comment by twa127** [comment] 2020-07-08 09:03
yes happy to close, I think the graphs are now usable again, I would like if we could show a message while they load, but that can wait for another day :-)

**Closed** 2020-07-08 16:56 UTC
